### ISSUE TITLE
Custom domain

### ISSUE THREAD

**Issue by ghost** [sachinraja/discordbotdash#4]
Hey so im looking so i can change it from 127.0.0.1 too my custom domain, would you be willing to please put a way to do that.

**Comment by sachinraja** [comment]
This is not something I can handle in the library. You may want to take a look at [this article on serving flask apps](https://www.digitalocean.com/community/tutorials/how-to-serve-flask-applications-with-gunicorn-and-nginx-on-ubuntu-18-04).

**Comment by ghost** [comment]
> This is not something I can handle in the library. You may want to take a look at [this article on serving flask apps](https://www.digitalocean.com/community/tutorials/how-to-serve-flask-applications-with-gunicorn-and-nginx-on-ubuntu-18-04).

Thanks, this should work!
